### PR TITLE
Make `Mock.Of<>` work with COM interop types that are annotated with `[CompilerGenerated]`

### LINKED ISSUE #1072: Mock.Of of Excel interop classes fails to initialize
I have a project that has a lot of tests on Excel interop classes.  
Those were working fine with my current test project (net452, Moq 4.8, Microsoft.Office.Interop.Excel v12.0.4518.1014, NUnit v3.12...)

But after upgrading to Moq 4.14 & Microsoft.Office.Interop.Excel v15.0.4795.1000, all the Mock.Of on interop classes fail to initialize.
I had other setup issues following interop upgrade (because they stated to use `dynamic` in some places, instead of `object`) but it seems that this is a different problem.

```
[Test]
public void Test_Works()
{
                var worksheet = new Mock<Worksheet>();
                var parent = new Mock<Workbook>();
                parent.Setup(x => x.FullName).Returns(string.Empty);
                worksheet.Setup(x => x.Parent).Returns(parent.Object);
}

[Test]
public void Test_Fails()
{
                var worksheet = new Mock<Worksheet>();
                var v = Mock.Of<Workbook>(x => x.FullName == string.Empty);
                worksheet.Setup(x => x.Parent).Returns(v);
}
```

The error is different based on the Moq version, but they all fail : 

Moq v4.13.1

```
  Message:
    System.ArgumentException : Method 'Moq.Language.Flow.IReturnsResult`1[Microsoft.Office.Interop.Excel.Workbook] Returns(System.String)' declared on type 'Moq.Language.IReturns`2[Microsoft.Office.Interop.Excel.Workbook,System.String]' cannot be called with instance of type 'Moq.Mock`1[System.String]'
  Stack Trace:
    Expression.ValidateCallInstanceType(Type instanceType, MethodInfo method)
    Expression.ValidateStaticOrInstanceMethod(Expression instance, MethodInfo method)
    Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
    MockSetupsBuilder.ConvertToSetup(Expression targetObject, Expression left, Expression right)
    MockSetupsBuilder.ConvertToSetupProperty(Expression targetObject, Expression left, Expression right)
    MockSetupsBuilder.ConvertToSetup(Expression left, Expression right)
    MockSetupsBuilder.VisitBinary(BinaryExpression node)
    BinaryExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    ExpressionVisitor.VisitLambda[T](Expression`1 node)
    Expression`1.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    ExpressionVisitor.VisitUnary(UnaryExpression node)
    MockSetupsBuilder.VisitUnary(UnaryExpression node)
    UnaryExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
    ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
    MockSetupsBuilder.VisitMethodCall(MethodCallExpression node)
    MethodCallExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    MockQueryable`1.Execute[TResult](Expression expression)
    Queryable.First[TSource](IQueryable`1 source, Expression`1 predicate)
    Mock.Of[T](Expression`1 predicate, MockBehavior behavior)
    Mock.Of[T](Expression`1 predicate)
    UnitTest1.Test_Fails() line 22
```

Moq v4.14.6

```
  Message:
    System.ArgumentException : Object instance was not created by Moq.
    Parameter name: mocked
  Stack Trace:
    Mock.Get[T](T mocked)
    lambda_method(Closure , Workbook )
    Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
    lambda_method(Closure )
    EnumerableExecutor`1.Execute()
    IQueryProvider.Execute[S](Expression expression)
    Queryable.First[TSource](IQueryable`1 source, Expression`1 predicate)
    lambda_method(Closure )
    MockQueryable`1.Execute[TResult](Expression expression)
    Queryable.First[TSource](IQueryable`1 source, Expression`1 predicate)
    Mock.Of[T](Expression`1 predicate, MockBehavior behavior)
    Mock.Of[T](Expression`1 predicate)
    UnitTest1.Test_Fails() line 22
```

Is it expected?
Do you have a workaround ?
Replacing all the `Mock.Of<>()` by `new Mock<>() + setup` is a lot of work and adds a lot of "useless" rows...

### PR DESCRIPTION
**Pull request by stakx**
This should fix #1072.

### CODE REVIEW

File: src/Moq/Linq/MockSetupsBuilder.cs [hunk 1]
```diff
@@ -151,7 +151,7 @@ private sealed class ReplaceMockObjectWithParameter : ExpressionVisitor
 
 			protected override Expression VisitMember(MemberExpression node)
 			{
-				if (node.Expression is ParameterExpression pe && pe.Type.IsDefined(typeof(CompilerGeneratedAttribute)))
+				if (node.Expression is ParameterExpression pe && pe.Type.IsDefined(typeof(CompilerGeneratedAttribute)) && pe.Type.Name.Contains("f__AnonymousType"))
```
Comment (stakx) [inline src/Moq/Linq/MockSetupsBuilder.cs:154]: For anyone wondering whether we can rely on that magic string to be present for anonymous types, this is based on Roslyn source code: [`/src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs`](https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs#L64-L73).
