### PR TITLE
Fix implementation of `Times.Equals`

### LINKED ISSUE #805: `Times.Equals` is implemented incorrectly
### Reproduction code:

```csharp
// see whether the kind of `Times` objects being compared is taken into account:
Assert.Equal(Times.Once(), Times.Exactly(1));

// see whether it is only the effective lower and upper bounds that get compared:
Assert.Equal(Times.Between(2, 3, Range.Inclusive), Times.Between(1, 4, Range.Exclusive));
```

### Actual behavior:

The first assertion passes, but the second one fails.

### Expected behavior:

Either both assertions should fail (meaning that the kind of `Times` being compared matters), or both should pass (meaning that only the effective lower and upper bounds matter).

`Times` is currently implemented in a way that leans towards the latter.

### PR DESCRIPTION
**Pull request by stakx**
Closes #805 (and applies some minor cleanup refactoring to `Times` while we're at it).

### CODE REVIEW

File: src/Moq/Times.cs [hunk 1]
```diff
@@ -10,14 +10,14 @@ namespace Moq
 	/// <include file='Times.xdoc' path='docs/doc[@for="Times"]/*'/>
 	public struct Times
 	{
-		private Func<int, bool> evaluator;
```
Comment (stakx) [inline src/Moq/Times.cs]: This makes a future generic extension point such as #355 impossible. That's however not an issue at all, as `Times` today implements equality comparison, and there is `IOccurrence`, both of which wouldn't work well together with a `Times.Matching(Func<int>)`.
