### PR TITLE
Remove leaked `MockVerificationException` and catch-throw-recatch cycle during verification

### LINKED ISSUE #507: `mock.Verify` and `mock.VerifyAll` leak internal `MockVerificationException` type
That exception type is delared `internal` and therefore cannot be specifically caught with a dedicated `catch` clause. But it can be seen in the exception message when it occurs.

This type was apparently introduced as an internal mechanism to aggregate mock exceptions during a broad `MockRepository.Verify` or `VerifyAll` call. Only `MockException` should be thrown directly.

### PR DESCRIPTION
**Pull request by stakx**
Closes #507.

### CODE REVIEW

File: Source/Obsolete/MockFactory.cs [hunk 1]
```diff
@@ -330,25 +329,23 @@ protected virtual void VerifyMocks(Action<Mock> verifyAction)
...
+			var failures = new List<UnmatchedSetups>();
 
 			foreach (var mock in mocks)
 			{
 				try
 				{
 					verifyAction(mock);
 				}
-				catch (MockVerificationException mve)
+				catch (MockException ex) when (ex.Error is UnmatchedSetups failure)
```
Comment (stakx) [inline Source/Obsolete/MockFactory.cs]: Unfortunately the throw-catch pattern cannot be replaced with a full try pattern due to this method's signature and the fact that it's `protected`. It would have to be marked as `[Obsolete]`.
