### PR TITLE
Fix `SetupAllProperties` indexer regression & refactor accessor check methods for clarify

### LINKED ISSUE #901: Regression in 4.12.0: `SetupAllProperties` resets indexer setups
### Code to reproduce:

```csharp
public interface IX
{
    string this[int index] { get; }
}

[Fact]
void SetupAllProperties_should_not_reset_indexer_setups()
{
    var mock = new Mock<IX>();
    mock.SetupGet(x => x[1]).Returns("value from setup");
    Assert.Equal("value from setup", mock.Object[1]);  // passes
    mock.SetupAllProperties();
    Assert.Equal("value from setup", mock.Object[1]);  // fails
}
```

This is caused by this line:

https://github.com/moq/moq4/blob/81d1fb24b5a9c5ceb443114b1657137501c4f9e5/src/Moq/SetupCollection.cs#L62

The filter condition should be more specific and rule out indexer accessors.

### PR DESCRIPTION
**Pull request by stakx**
Fixes #901.

### CODE REVIEW

File: src/Moq/StringBuilderExtensions.AppendExpression.cs [hunk 1]
```diff
@@ -327,39 +328,49 @@ private static StringBuilder AppendExpression(this StringBuilder builder, Method
...
-					builder.Append('.')
-					       .Append(expression.Method.Name, 4);
-					if (expression.Arguments.Count > paramFrom)
+					if (expression.Method.IsPropertyAccessor())
+					{
+						builder.Append('.')
+						       .Append(expression.Method.Name, 4);
+						if (expression.Arguments.Count > paramFrom)
+						{
+							builder.AppendCommaSeparated("[", expression.Arguments.Skip(paramFrom), AppendExpression, "]");
```
Comment (stakx) [inline src/Moq/StringBuilderExtensions.AppendExpression.cs]: Not introduced by this refactoring, but weird nonetheless: Why do angle brackets appear in the formatting of a property getter expression?

File: src/Moq/SetupCollection.cs [hunk 2]
```diff
@@ -32,7 +32,7 @@ public void Add(Setup setup)
 		{
 			lock (this.setups)
 			{
-				if (setup.Method.LooksLikeEventAttach() || setup.Method.LooksLikeEventDetach())
+				if (setup.Method.IsEventAddAccessor() || setup.Method.IsEventRemoveAccessor())
```
Comment (stakx) [inline src/Moq/SetupCollection.cs]: For consistency, add a `.IsEventAccessor()` check method.

Comment (stakx) [reply src/Moq/SetupCollection.cs]: Left as is for now, as the new method would be used in only two places, and not introduce any opportunities for optimization.
