### PR TITLE
Match indexers used as arguments in setup expression eagerly

### LINKED ISSUE #714: ArgumentOutOfRangeException when setup expression contains indexer access
I'm getting an ArgumentOutOfRangeException when my Setup expression contains accessing an object in an array at an index.

```
_Helper.Setup(s => s.Parse(containers[i]));
```

This can be remedied by first accessing the object at the index.

```
var currentContainer = containers[i];
_Helper.Setup(s => s.Parse(currentContainer));
```

If this is intended behavior, could Moq be enhanced to detect this type of expression and throw an exception with a helpful message? This would add value in troubleshooting these expressions.

Below is some code to reproduce the exception and the result stack trace.

```
public class Container
{
    public int MyProperty { get; set; }
}
public interface IHelper
{
    void Parse(Container container);
}
public class Parser
{
    IHelper _Helper;
    public Parser(IHelper helper)
    {
        _Helper = helper;
    }
    public void Parse(List<Container> containers)
    {
        foreach (var container in containers)
            _Helper.Parse(container);
    }
}
[TestFixture]
public class HelperTests
{
    Mock<IHelper> _Helper;
    Parser _Parser;
    [SetUp]
    public void SetUp()
    {
        _Helper = new Mock<IHelper>();
        _Parser = new Parser(_Helper.Object);
    }
    [Test]
    public void Parse()
    {
        var containers = new List<Container> { new Container() };
        for (var i = 0; i < containers.Count; i++)
            _Helper.Setup(s => s.Parse(containers[i]));
        _Parser.Parse(containers);
    }
}
```

```
Result StackTrace:	
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Moq.Evaluator.SubtreeEvaluator.Evaluate(Expression e) in C:\projects\moq4\src\Moq\Evaluator.cs:line 73
   at Moq.Matchers.LazyEvalMatcher.Matches(Object value) in C:\projects\moq4\src\Moq\Matchers\LazyEvalMatcher.cs:line 20
   at Moq.InvocationShape.IsMatch(Invocation invocation) in C:\projects\moq4\src\Moq\InvocationShape.cs:line 52
   at Moq.SetupCollection.FindMatchFor(Invocation invocation) in C:\projects\moq4\src\Moq\SetupCollection.cs:line 63
   at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock) in C:\projects\moq4\src\Moq\Interception\InterceptionAspects.cs:line 117
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in C:\projects\moq4\src\Moq\Interception\Mock.cs:line 21
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at UnitTests.Parser.Parse(List`1 containers) in REDACTED
   at UnitTests.HelperTests.Parse() in REDACTED
--ArgumentOutOfRangeException
   at lambda_method(Closure )
Result Message:	
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
```

### PR DESCRIPTION
**Pull request by stakx**
This resolves #714.

It doesn't make sense for indexers to be matched lazily when other properties are being matched eagerly, so this will make Moq a little more consistent.

(While technically a small breaking change, making it anyway seems permissible because Moq has neglected indexers far too long and essentially left its behavior regarding them semi-unspecified.)

### CODE REVIEW

File: src/Moq/MatcherFactory.cs [hunk 1]
```diff
@@ -132,9 +132,13 @@ internal static class MatcherFactory
 				}
 #pragma warning restore 618
 
-				return new Pair<IMatcher, Expression>(new LazyEvalMatcher(originalExpression), originalExpression);
+				var method = call.Method;
+				if (!method.IsPropertyGetter() && !method.IsPropertyIndexerGetter())
```
Comment (stakx) [inline src/Moq/MatcherFactory.cs]: This actually does a little more than target indexers. It also makes sure that if somehow a property or index expression has made it into the setup expression in the form of a `get_*` method call, we recognize them anyway.
