### PR TITLE
`System.Object` methods should always work.

### LINKED ISSUE #248: Allow setting up "overrides" for `object` members when mocking interfaces
Consider the following mock of some interface:

    var mock = new Mock<IMyThing>();
    mock.Setup(s => s.Equals(It.IsAny<object>())).Returns<object>(x =>
    {
        if (typeof(IMyThing).IsAssignableFrom(x.GetType()))
        {
            ...
        }
        return false;
    });

    var myThing = mock.Object;

There is no interceptor created for the `Equals()` method. But since I know every object implementing `IMyThing` will also be an `object` wouldn't it be nice if I was able to do this?

### LINKED ISSUE #273: Somethings up with strict mock with recent changes
When using strict moq I am getting inconsistent errors. I'm using MOQ and Autofixture in my main project where I am getting failed tests for Object.ToString() not being set up for a strict Mock. Using this in a vanilla project I get Object.GetHashCode not set up on a strict mock. I may be missing something easy but attached is a sample test project

[Moq4516Tests.zip](https://github.com/moq/moq4/files/374667/Moq4516Tests.zip)

Test Name:	GetHashCodeTestFailure
Test FullName:	Moq4516Tests.UnitTests.GetHashCodeTestFailure
Test Source:	C:\Users\wwebb\Documents\Visual Studio 2015\Projects\Moq4516Tests\Moq4516Tests\UnitTest1.cs : line 54
Test Outcome:	Failed
Test Duration:	0:00:00.3059009

Result StackTrace:	
at Moq.ExtractProxyCall.HandleIntercept(ICallContext invocation, InterceptorContext ctx, CurrentInterceptContext localctx)
   at Moq.Interceptor.Intercept(ICallContext invocation)
   at Moq.Proxy.CastleProxyFactory.Interceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ObjectProxy.GetHashCode()
   at Moq.Interceptor.ExpressionKey.GetHashCode()
   at System.Collections.Generic.ObjectEqualityComparer`1.GetHashCode(T obj)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Moq.Interceptor.AddCall(IProxyCall call, SetupKind kind)
   at Moq.Mock.<>c__DisplayClass61_0`2.<Setup>b__0()
   at Moq.PexProtector.Invoke[T](Func`1 function)
   at Moq.Mock.Setup[T,TResult](Mock`1 mock, Expression`1 expression, Condition condition)
   at Moq.Mock`1.Setup[TResult](Expression`1 expression)
   at Moq4516Tests.UnitTests.GetHashCodeTestFailure() in C:\Users\wwebb\Documents\Visual Studio 2015\Projects\Moq4516Tests\Moq4516Tests\UnitTest1.cs:line 60
Result Message:	
Test method Moq4516Tests.UnitTests.GetHashCodeTestFailure threw exception: 
Moq.MockException: Object.GetHashCode() invocation failed with mock behavior Strict.
All invocations on the mock must have a corresponding setup.

### PR DESCRIPTION
**Pull request by kolomanschaft**
Even in strict mode if none of them were set up. Fixes #273 and closes #248.

### CODE REVIEW

**Comment by kolomanschaft** [comment]
@kzu: I solved it by extending the `ToString` intercept strategy. I'm not sure about the choice I've made with the return value of `GetHashCode` though. What do you think?

File: Source/InterceptorStrategies.cs [hunk 1]
```diff
@@ -133,25 +133,42 @@ public InterceptionAction HandleIntercept(ICallContext invocation, InterceptorCo
...
+	internal class InterceptObjectMethodsMixin : IInterceptStrategy
 	{
 		public InterceptionAction HandleIntercept(ICallContext invocation, InterceptorContext ctx, CurrentInterceptContext localctx)
 		{
 			var method = invocation.Method;
 
-			// Only if there is no corresponding setup
-			if (IsObjectToStringMethod(method) && !ctx.OrderedCalls.Select(c => IsObjectToStringMethod(c.Method)).Any())
+			// Only if there is no corresponding setup for `ToString()`
+			if (IsObjectMethod(method, "ToString") && !ctx.OrderedCalls.Select(c => IsObjectMethod(c.Method, "ToString")).Any())
```
Comment (kzu) [inline Source/InterceptorStrategies.cs]: We should probably switch to using `nameof(object.ToString)` now that C# 6 is here :)

**Comment by kzu** [comment]
Looks good to me, thanks @kolomanschaft !
