### PR TITLE
Fail when implicit conversion operator renders argument matcher unmatchable

### LINKED ISSUE #897: Method without setup not return null
Hi,
I make a MockTestCase project : https://github.com/michelcedric/MockTestCase/blob/master/MockTest/UnitTest1.cs

When a method without setup is defined normaly he returns null.
But If the return it's a IEnumerable, it's return an empty list.

I think it's a strange behavior and I don't understand why not return null?

Best regards

Cédric Michel

### PR DESCRIPTION
**Pull request by stakx**
Closes #897, #898.

### CODE REVIEW

**Comment by stakx** [comment]
@michelcedric: With this proposed change, your `DateTimeNotWorking` test from #897 would fail here:

> ```csharp
> serviceMock.Setup(s => s.GetDataList(It.IsAny<DateTime>())).Returns(_data);
> ```

with the following message:

> **System.ArgumentException**: Matcher `It.IsAny<DateTime>()` is unmatchable: An implicit conversion operator will convert arguments of type `DateTime` to the parameter's type `DateTimeOffset`, which is assignment-incompatible.

Do you think this will be a clear enough indication of why the setup is written incorrectly?

**Comment by michelcedric** [comment]
Yes thanks

File: src/Moq/MatcherFactory.cs [hunk 1]
```diff
@@ -33,6 +35,23 @@ internal static class MatcherFactory
 
 		public static Pair<IMatcher, Expression> CreateMatcher(Expression argument, ParameterInfo parameter)
 		{
+			if (argument.NodeType == ExpressionType.Convert)
+			{
+				var convertExpression = (UnaryExpression)argument;
+				if (convertExpression.Method?.Name == "op_Implicit")
```
Comment (stakx) [inline src/Moq/MatcherFactory.cs]: Perhaps we could take `op_Implicit` handling even further and evaluate it if it isn't applied to an argument matcher.

File: tests/Moq.Tests/UnmatchableMatchersFixture.cs [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+			var mock = new Mock<IX>();
+			mock.Setup(x => x.USeNullableLong(It.IsAny<long>()));
+		}
+
+		public interface IX
+		{
+			void UseDateTimeOffset(DateTimeOffset arg);
+			void UseInt(int arg);
+			void UseLong(long arg);
+			void USeNullableLong(long? arg);
```
Comment (stakx) [inline tests/Moq.Tests/UnmatchableMatchersFixture.cs]: Typo: `USe` &rarr; `Use`

File: tests/Moq.Tests/UnmatchableMatchersFixture.cs [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+
+namespace Moq.Tests
+{
+	public class UnmatchableMatchersFixture
+	{
+		[Fact]
+		public void Matchers_that_are_unmatchable_due_to_implicit_conversion_operator_cause_setup_failure()
+		{
+			var mock = new Mock<IX>();
+			var ex = Assert.Throws<ArgumentException>(() => mock.Setup(x => x.UseDateTimeOffset(It.IsAny<DateTime>())));
```
Comment (stakx) [inline tests/Moq.Tests/UnmatchableMatchersFixture.cs]: For the sake of these tests' independence from external factors, perhaps they shouldn't rely on external types (even ones from the BCL). It might be wiser to define our own types with a `implicit operator`. This would make the operator directly visible and thus make the problem at hand easier to understand.
