### PR TITLE
Changed TypeNotMockable exception message

### LINKED ISSUE #1112: TypeNotMockable Exception
Can the Moq Gaurd class exception below also return the type name? it would be very helpful when mocking objects that take multiple constructor parameters.

		public static void IsMockable(Type type)
		{
			if (!type.IsMockable())
			{
				throw new NotSupportedException(Resources.TypeNotMockable);
			}
		}

### PR DESCRIPTION
**Pull request by jacker92**
Modified Exception message to include the type name. 

Fixes #1112

### CODE REVIEW

File: src/Moq/Guard.cs [hunk 1]
```diff
@@ -204,7 +204,10 @@ public static void IsMockable(Type type)
 		{
 			if (!type.IsMockable())
 			{
-				throw new NotSupportedException(Resources.TypeNotMockable);
+				throw new NotSupportedException(
+					string.Format(
+						Resources.TypeNotMockable,
+						type.Name));
```
Comment (stakx) [inline src/Moq/Guard.cs]: For consistency with existing code, please use the `type.GetFormattedName()` extension method:

```suggestion
						type.GetFormattedName()));
```

File: src/Moq/Properties/Resources.resx [hunk 2]
```diff
@@ -121,7 +121,7 @@
     <value>Expression {0} involves a field access, which is not supported. Use properties instead.</value>
   </data>
   <data name="TypeNotMockable" xml:space="preserve">
-    <value>Type to mock must be an interface, a delegate, or a non-sealed, non-static class.</value>
+    <value>Mocked type {0} must be an interface, a delegate, or a non-sealed, non-static class.</value>
```
Comment (stakx) [inline src/Moq/Properties/Resources.resx]: Since the type isn't actually mocked yet, _"mocked type"_ is less correct than the existing phrasing, _"type to mock"_. I'd suggest changing this to:

```suggestion
    <value>Type to mock ({0}) must be an interface, a delegate, or a non-sealed, non-static class.</value>
```

**Review by stakx — CHANGES_REQUESTED** [review]
Just two small details, then we should be good to go!

File: src/Moq/Properties/Resources.Designer.cs [hunk 3]
```diff
@@ -572,7 +572,7 @@ internal class Resources {
         }
         
         /// <summary>
-        ///   Looks up a localized string similar to Type to mock must be an interface, a delegate, or a non-sealed, non-static class..
+        ///   Looks up a localized string similar to Mocked type {0} must be an interface, a delegate, or a non-sealed, non-static class..
```
Comment (stakx) [inline src/Moq/Properties/Resources.Designer.cs]: Please have VS regenerate this file so that it is in sync with `Resources.resx`.

**Review by stakx — CHANGES_REQUESTED** [review]

**Review by stakx — APPROVED** [review]
